Make scopes editable
IMGIITRoorkee/omniport-service-developer pull request #4
Opened 2021-12-30 13:30 UTC by ranasiddharth

Change approved status(if True) of app to False after scope editing

2021-12-30 14:05 UTC, kmrinal19 requested changes

2021-12-30 14:05 UTC, kmrinal19 commented on views/application.py
> +            if (set(instance.data_points) == set(request.data.get('data_points'))):
The entire `if else` can be replaced with following
```
if not (set(instance.data_points) == set(request.data.get('data_points'))):
    instance.is_approved = False
```

2021-12-30 14:05 UTC, kmrinal19 commented on views/application.py
> +        if "data_points" in request.data:
I think that this `if` statement can be clubbed with the `if` statement below

2021-12-30 14:43 UTC, ranasiddharth commented on views/application.py
> +            if (set(instance.data_points) == set(request.data.get('data_points'))):
Changes made

2021-12-30 14:44 UTC, ranasiddharth commented on views/application.py
> +        if "data_points" in request.data:
Changes made

2021-12-30 15:12 UTC, ranasiddharth commented on views/application.py
> +        if "data_points" in request.data:
Comments changed from doc string to block in final commit

2021-12-30 15:37 UTC, kmrinal19 approved these changes

2021-12-31 15:03 UTC, rish9101 approved these changes

2022-01-14 09:36 UTC, merged